import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trannqt
 */
public class formMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form formMonHoc
     */
//    public formMonHoc() {
//        initComponents();
//    }
    private final MonHoc monhoc = new MonHoc();
        private final DefaultTableModel tableModel = new DefaultTableModel();
        private boolean check = true;
        public formMonHoc() throws SQLException{
            initComponents(); // Khởi tạo các components trên JFrame
            String []colsName = {"Mã môn học", "Tên môn học"};
            tableModel.setColumnIdentifiers(colsName);
            tableMonHoc.setModel(tableModel);
            ShowData();
            setNull();
            setKhoa(false);
            setButton(true);
        }

    public void ShowData() throws SQLException{
        ResultSet result= monhoc.ShowMonHoc();
        try {
            while(result.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
                String rows[] = new String[2];
                rows[0] = result.getString(1); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
                rows[1] = result.getString(2); // lấy dữ liệu tai cột số 2 ứng với tên hàng
    //            rows[3] = result.getString(4); 
                tableModel.addRow(rows); // đưa dòng dữ liệu vào tableModel
            //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update
            }
        }
        catch (SQLException e) {
        }
    } 
    
    
    //Ham xoa du lieu trong tableModel
 public void ClearData() throws SQLException{
 //Lay chi so dong cuoi cung
    int n=tableModel.getRowCount()-1;
    for(int i=n;i>=0;i--)
        tableModel.removeRow(i);//Remove tung dong
 }
    //Ham xoa cac TextField
    private void setNull()
    {
    //Xoa trang cac JtextField
       this.txtMaMH.setText(null);
       this.txtTenMH.setText(null);
       this.txtMaMH.requestFocus();
    }
    //Ham khoa cac TextField
    private void setKhoa(boolean a)
    {
        //Khoa hoac mo khoa cho Cac JTextField
        this.txtMaMH.setEnabled (!a);
        this.txtTenMH.setEnabled (!a);
    }
    //Ham khoa cac Button
    private void setButton(boolean a)
    {
        //Vo hieu hoac co hieu luc cho cac JButton
        this.btnLuuMH.setEnabled (a);
        this.btnXoaMH.setEnabled (a);
        this.btnSuaMH.setEnabled (a);
        this.btnLuuMH.setEnabled (!a);
        this.btnHuyMH.setEnabled (!a);
//     this.btThoat.setEnabled (a);
     } 
                                             

    public void showTheoMaMH(String ml) throws SQLException{
    ResultSet result= monhoc.getMonHocByID(ml);
    try {
        while(result.next()){ // nếu còn đọc tiếp được một dòng dữ liệu
            
            txtMaMH.setText(result.getString(1)); // lấy dữ liệu tại cột số 1 (ứng với mã hàng)
            txtTenMH.setText(result.getString(2)); // lấy dữ liệu tai cột số 2 ứng với tên hàng
//            rows[3] = result.getString(4); 
 // đưa dòng dữ liệu vào tableModel
        //mỗi lần có sự thay đổi dữ liệu ở tableModel thì Jtable sẽ tự động update
        }
    }
    catch (SQLException e) {
    }
 } 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMonHoc = new javax.swing.JTable();
        btnThemMH = new javax.swing.JButton();
        btnXoaMH = new javax.swing.JButton();
        btnSuaMH = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaMH = new javax.swing.JTextField();
        txtTenMH = new javax.swing.JTextField();
        btnLuuMH = new javax.swing.JButton();
        btnHuyMH = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý môn học");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ MÔN HỌC");

        tableMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMonHoc);

        btnThemMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add-1-icon-16p.png"))); // NOI18N
        btnThemMH.setText("Thêm");
        btnThemMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMHActionPerformed(evt);
            }
        });

        btnXoaMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button-Close-icon-16p.png"))); // NOI18N
        btnXoaMH.setText("Xóa");
        btnXoaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMHActionPerformed(evt);
            }
        });

        btnSuaMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/note-edit-icon.png"))); // NOI18N
        btnSuaMH.setText("Sửa");
        btnSuaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaMHActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã môn học");

        jLabel3.setText("Tên môn học");

        btnLuuMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/floppy-icon-16.png"))); // NOI18N
        btnLuuMH.setText("Lưu");
        btnLuuMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuMHActionPerformed(evt);
            }
        });

        btnHuyMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/arrow-return-180-left-icon.png"))); // NOI18N
        btnHuyMH.setText("Hủy");
        btnHuyMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyMHActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clipboard-sign-out-icon-16.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaMH)
                            .addComponent(txtTenMH)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuyMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuuMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuyMH, btnLuuMH, btnSuaMH, btnThemMH, btnXoaMH});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemMH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaMH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLuuMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyMH)
                    .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHuyMH, btnSuaMH, btnThemMH, btnXoaMH, jButton1});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMHActionPerformed
        // TODO add your handling code here:                                          
        // TODO add your handling code here:
        setNull();//Xoa trang TextField
        setKhoa(false);//Mo khoa TextField
        setButton(false);//Goi ham khoa cac Button
        check=true;//Gan cothem = true de ghi nhan trang thai them moi

    }//GEN-LAST:event_btnThemMHActionPerformed

    private void btnXoaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMHActionPerformed
        // TODO add your handling code here:
        String ma=txtMaMH.getText();
        try {
            if(ma.length()==0)
                JOptionPane.showMessageDialog(null,"Cần chọn 1 môn học để xoá","Thông báo",1);
            else
            {
            if(JOptionPane.showConfirmDialog(null, "Bạn muốn xóa không?","Thông báo",2)==0)
            {
                monhoc.DeleteData(ma);//goi ham xoa du lieu theo ma loai
                JOptionPane.showMessageDialog(null, "Xóa thành công!", "Thông báo", 1);
                ClearData();//Xoa du lieu trong tableModel
                ShowData();//Do du lieu vao table Model
                setNull();//Xoa trang Textfield
            }
            }
            }
            catch (SQLException ex) {
            Logger.getLogger(formMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }//GEN-LAST:event_btnXoaMHActionPerformed

    private void btnSuaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMHActionPerformed
        // TODO add your handling code here:
        String mh=txtMaMH.getText();
        if(mh.length()==0) //Chua chon Ma loai
            JOptionPane.showMessageDialog(null,"Vui lòng chọn môn học cần sửa","Thôngg báo",1);
        else
        {
            setKhoa(false);//Mo khoa cac TextField
            setButton(false); //Khoa cac Button
            txtMaMH.enable(false);
            check=false; //Gan cothem=false de ghi nhan trang thai la sua
        }
    }//GEN-LAST:event_btnSuaMHActionPerformed

    private void btnLuuMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuMHActionPerformed
        // TODO add your handling code here:

        String mh=txtMaMH.getText();
        String tmh=txtTenMH.getText();
        
        if(mh.length()==0 || tmh.length()==0)
            JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin!","Thông báo",1);
        else{
            try{
                Integer.parseInt(tmh);
                JOptionPane.showMessageDialog(this, "Tên môn học phải có số và chữ","Thông báo",1);
            }
            catch(Exception ex ){
                try {
                    if(check==true){ //Luu cho tthem moi
                        monhoc.InsertData(mh, tmh);
                        JOptionPane.showMessageDialog(null, "Thêm thành công!", "Thông báo", 1);
                    }
                    else{ //Luu cho sua
                        monhoc.EditData(mh, tmh);
                        JOptionPane.showMessageDialog(null, "Sửa thành công!", "Thông báo", 1);
                    }
                    ClearData(); //lúc thêm sẽ add cả table=table+table, nên chúng ta phải xóa bớt 1 table chỉ giữ lại cái cuối cùng
                    ShowData(); //Do lai du lieu vao Table Model
                }
                catch (SQLException exx) {
                    JOptionPane.showMessageDialog(null,"Cập nhật dữ liệu thất bại!","Thông báo",1);
                }
                setKhoa(false);
                setButton(true);
            }
            }            
    }//GEN-LAST:event_btnLuuMHActionPerformed

    private void btnHuyMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyMHActionPerformed
        // TODO add your handling code here:
        setNull();
        setKhoa(false);
        setButton(true);
    }//GEN-LAST:event_btnHuyMHActionPerformed

    private void tableMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMonHocMouseClicked
        // TODO add your handling code here:                                        
        
        //Hien thi du lieu len cac JTextField khi Click chuot vao JTable
        try{
            //Lay chi so dong dang chon
            int row =this.tableMonHoc.getSelectedRow();
            String ml=(this.tableMonHoc.getModel().getValueAt(row,0)).toString();
//            System.out.print(ml);
            showTheoMaMH(ml);//Goi ham lay du lieu theo ma loai
//            if(rs.next())//Neu co du lieu
//            {
//            this.txtMaloai.setText(rs.getString("Maloai"));
//            this.txtTenloai.setText(rs.getString("Tenloai"));
//            }
        }
        catch (SQLException e) {
        }  
    }//GEN-LAST:event_tableMonHocMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMonHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formMonHoc().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formMonHoc.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuyMH;
    private javax.swing.JButton btnLuuMH;
    private javax.swing.JButton btnSuaMH;
    private javax.swing.JButton btnThemMH;
    private javax.swing.JButton btnXoaMH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableMonHoc;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtTenMH;
    // End of variables declaration//GEN-END:variables
}
