/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.print.*;
import java.text.*;
import javax.swing.JTable;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class formHB extends javax.swing.JFrame {

    /**
     * Creates new form formHB
     */
    /*public formHB() {
        initComponents();
    }*/
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private boolean check = true;
    private final ThongKe thongke = new ThongKe();
    private final HocPhan hocphan = new HocPhan();

    public formHB() throws SQLException {
        initComponents();
        String[] colsName = {"Mã số sinh viên", "Họ và Tên", "Tên khoa", "Điểm tổng", "Điểm rèn luyện"};
        tableModel.setColumnIdentifiers(colsName);
        hbtable.setModel(tableModel);

        addCombobox();
        ShowData();
    }

    public void addCombobox() throws SQLException {
//        Khoa khoa = new Khoa();0
        ResultSet res = hocphan.getHocKy();
        while (res.next()) {
//            String makhoa = khoa.getMaKhoa(res.getString(1)).toString();
            cbbHocKy.addItem(res.getString(1));
//            cbbMaKhoa.setSelectedItem(makhoa);
//            System.err.println("get: "+makhoa+" "+cbbMaKhoa.getSelectedItem().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Printbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hbtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbHocKy = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách nhận học bổng");

        Printbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Printer-blue-icon.png"))); // NOI18N
        Printbtn.setText("In danh sách");
        Printbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintbtnActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clipboard-sign-out-icon-16.png"))); // NOI18N
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        hbtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(hbtable);

        jLabel1.setText("DANH SÁCH NHẬN HỌC BỔNG");

        jLabel2.setText("Học kỳ:");

        cbbHocKy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbHocKyItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Printbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbbHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbHocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Printbtn))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Printbtn, jButton2});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrintbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintbtnActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Danh sách sinh viên nhận học bổng");
        Calendar cal = new GregorianCalendar();
               int month =cal.get(Calendar.MONTH);
               int year =cal.get(Calendar.YEAR);
               int day =cal.get(Calendar.DAY_OF_MONTH);
        
        MessageFormat footer = new MessageFormat("Trang {0,number,integer}" +"                         Ngày in "+day+"/"+(month+1)+"/"+year);
        try {
            hbtable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Không in được ", e.getMessage());
        }
    }//GEN-LAST:event_PrintbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void ClearData() throws SQLException {
        //Lay chi so dong cuoi cung
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);//Remove tung dong
        }
    }

    public void clearCombobox() {
        cbbHocKy.removeAllItems();
    }

    private void cbbHocKyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbHocKyItemStateChanged
        try {
            // TODO add your handling code here:
//        clearCombobox();
ShowData();
        } catch (SQLException ex) {
            Logger.getLogger(formHB.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cbbHocKyItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formHB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new formHB().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(formHB.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public boolean check(String masv,int hocky) throws SQLException {
        int sl = 0;
        ResultSet res = hocphan.getSinhVienRot(masv,hocky);
        while (res.next()) {
            sl++;
        }
        if (sl == 0) {
            return true;
        } else {
            return false;
        }
    }

    public void ShowData() throws SQLException {
//        ClearData();
//        String hk = cbbHocKy.getSelectedItem().toString();
//        System.err.println("học kỳ: " + hk);
//        int hocky = 1;
//        try {
//            hocky = Integer.parseInt(hk);
//        } catch (Exception e) {
//            System.err.println("error HocKy");
//        }
////        if(check(hocky)){
//        ResultSet result = thongke.getSVNhanHocBong(hocky);
//
//        try {
//            while (result.next()) {
//
//                String rows[] = new String[5];
//                rows[0] = result.getString(1);
//                rows[1] = result.getString(2);
//                rows[2] = result.getString(3);
//                rows[3] = result.getString(4);
//                rows[4] = result.getString(5);
//
//                //rows[2] = result.getString(8);
//                /*String c; 
//                    c = rows[2];
//                    c = result.getString(8);//= result.getString(8); //diem tong ket
//                 */
// /*int d;
//                    d = Integer.parseInt(c,29);*/
// /*if(d>8){
//                        rows[2] = result.getString(8);
//                    }
//                 */
//                tableModel.addRow(rows);
//            }
//        } catch (SQLException e) {
//        }

   
        ClearData();
    
        String hk = cbbHocKy.getSelectedItem().toString();
        System.err.println("học kỳ: " + hk);
        int hocky = 1;
        try {
            hocky = Integer.parseInt(hk);
        } catch (Exception e) {
            System.err.println("error HocKy");
        }
//        if(check(hocky)){
        ResultSet result = thongke.getSVNhanHocBong(hocky);
        int i=0;
        String dssv[]=new String[500];
            while (result.next()) {
                dssv[i]=result.getString(1);
                i++;
            }
            for(int j=0;j<i;j++){
                System.err.println("dssv: "+dssv[j]);
                if(check(dssv[j],hocky)){
                    System.err.println("duoc nhan hoc bong");
                    ResultSet ok = null;
                    ok = thongke.getDSSV(dssv[j]);
                    System.err.println("masv: "+dssv[j]);
                    try{
                        while(ok.next()){
                            String rows[] = new String[5];
                            rows[0] = ok.getString(1);
                            rows[1] = ok.getString(2);
                            rows[2] = ok.getString(3);
                            rows[3] = ok.getString(4);
                            rows[4] = ok.getString(5);

                        tableModel.addRow(rows);
                        }
                    }catch(Exception e){
                        System.err.println(e);
                    }
                }
            }
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Printbtn;
    private javax.swing.JComboBox<String> cbbHocKy;
    private javax.swing.JTable hbtable;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
